version: "3.9"

services:
  flask:
    build: .
    container_name: firefly-management-app
    pull_policy: build
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
    ports:
      - "${APP_PORT}:${FLASK_PORT}"
